upstream sio_backend_active {
    server sio-backend-blue:3000;
}

# AMBIENTE PROD
server{
    listen 80;
    server_name localhost;
    location / {
        proxy_pass http://fe-prod:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio_backend_active;
    }
}

# AMBIENTE TEST
server{
    listen 8080;
    location / {
        proxy_pass http://fe-test:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio_backend_active;
    }
}

# AMBIENTE SVI
server{
    listen 8999;
    location / {
        proxy_pass http://fe-sio:80;
    }
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sio_backend_active;
    }
}